name: 1.0$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPack: 'Application'
  SolutionName: 'MLH.DeeplTranslations.sln'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    name: Azure Pipelines
    vmImage: windows-2019 # note that the Resharper CLT will only work on a windows machine or container
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      SolutionName: $(SolutionName)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Pack_And_Publish_To_NuGet.yaml@ALMStuff
    parameters:
      FolderToPack: $(FolderToPack)
